services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:admin@mongodb-local:27017
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - mongodb-local
      - dynamodb-local
    restart: unless-stopped

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    restart: unless-stopped

  mongodb-local:
    image: mongo:latest
    container_name: mongodb-local
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    command: mongod --bind_ip_all

volumes:
  mongodb_data: 